---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: socket
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
spec:
  rules:
    - host: check.my.lol
      http:
        paths: 
         - path: /socket
           backend:
              serviceName: test-socket
              servicePort: 80
    
    