---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8dash
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: traefik.example.com
    http:
      paths:
      - path: /dash
        backend:
          serviceName: k8dash
          servicePort: 80
